"""Pydantic 领域模型."""

from inkflow.domain.models.agent_pipeline import (
    PipelineConfig,
    PipelineExecuteRequest,
    RoleOverride,
)
from inkflow.domain.models.chapter import (
    Chapter,
    ChapterCreate,
    ChapterStatus,
    ChapterUpdate,
    StatusHistoryEntry,
    Volume,
    VolumeCreate,
    VolumeUpdate,
)
from inkflow.domain.models.character import (
    Character,
    CharacterCreate,
    CharacterExtractionResult,
    CharacterExtractRequest,
    CharacterGroup,
    CharacterRelation,
    CharacterRelationCreate,
    CharacterUpdate,
    ExtractedCharacter,
    ExtractedRelation,
)
from inkflow.domain.models.context import (
    ChapterSummary,
    ContextAssemblyResult,
    ContextBlock,
    ContextItem,
    ContextLayer,
    ContextRequest,
    ContextSourceType,
    DroppedItem,
    TokenBudgetConfig,
)
from inkflow.domain.models.extraction import (
    ExtractionRequest,
    ExtractionResult,
    ExtractionRun,
    ExtractionStatus,
    ExtractionType,
    ReindexResult,
)
from inkflow.domain.models.foreshadowing import (
    ExtractedForeshadowing,
    Foreshadowing,
    ForeshadowingCreate,
    ForeshadowingExtractionResult,
    ForeshadowingExtractRequest,
    ForeshadowingStatus,
    ForeshadowingUpdate,
)
from inkflow.domain.models.outline import (
    GeneratedArc,
    GeneratedOutline,
    GeneratedPlotPoint,
    Outline,
    OutlineCreate,
    OutlineGenerateRequest,
    OutlineGenerationResult,
    OutlineUpdate,
    PlotPoint,
    PlotPointCreate,
    PlotPointUpdate,
    StoryArc,
    StoryArcCreate,
    StoryArcUpdate,
)
from inkflow.domain.models.project import Project, ProjectConfig, ProjectCreate, ProjectUpdate
from inkflow.domain.models.timeline import (
    ConsistencyReport,
    ExtractedTimelineEvent,
    TimelineConflict,
    TimelineEvent,
    TimelineEventCreate,
    TimelineEventRef,
    TimelineEventUpdate,
    TimelineExtractionResult,
    TimelineExtractRequest,
    TimelineView,
)
from inkflow.domain.models.world import (
    ExtractedWorldSetting,
    WorldCreate,
    WorldExtractionResult,
    WorldExtractRequest,
    WorldSetting,
    WorldUpdate,
)
from inkflow.domain.models.writing import (
    ContinueWritingRequest,
    FormatValidationResult,
    RevisionRequest,
    WritingMode,
    WritingRequest,
    WritingResult,
)

__all__ = [
    "PipelineConfig",
    "PipelineExecuteRequest",
    "RoleOverride",
    "Project",
    "ProjectConfig",
    "ProjectCreate",
    "ProjectUpdate",
    "Chapter",
    "ChapterCreate",
    "ChapterStatus",
    "ChapterUpdate",
    "StatusHistoryEntry",
    "Volume",
    "VolumeCreate",
    "VolumeUpdate",
    # ── character (F9) ──
    "Character",
    "CharacterCreate",
    "CharacterUpdate",
    "CharacterGroup",
    "CharacterRelation",
    "CharacterRelationCreate",
    "ExtractedCharacter",
    "ExtractedRelation",
    "CharacterExtractRequest",
    "CharacterExtractionResult",
    "WritingMode",
    "WritingRequest",
    "ContinueWritingRequest",
    "RevisionRequest",
    "WritingResult",
    "FormatValidationResult",
    # ── context (F6) ──
    "ContextLayer",
    "ContextSourceType",
    "ContextItem",
    "ContextBlock",
    "DroppedItem",
    "ChapterSummary",
    "TokenBudgetConfig",
    "ContextRequest",
    "ContextAssemblyResult",
    # ── extraction (F14) ──
    "ExtractionType",
    "ExtractionStatus",
    "ExtractionRequest",
    "ExtractionResult",
    "ExtractionRun",
    "ReindexResult",
    # ── world (F10) ──
    "WorldSetting",
    "WorldCreate",
    "WorldUpdate",
    "ExtractedWorldSetting",
    "WorldExtractRequest",
    "WorldExtractionResult",
    # ── outline (F11) ──
    "Outline",
    "OutlineCreate",
    "OutlineUpdate",
    "PlotPoint",
    "PlotPointCreate",
    "PlotPointUpdate",
    "StoryArc",
    "StoryArcCreate",
    "StoryArcUpdate",
    "GeneratedOutline",
    "GeneratedPlotPoint",
    "GeneratedArc",
    "OutlineGenerateRequest",
    "OutlineGenerationResult",
    # ── timeline (F12) ──
    "TimelineEvent",
    "TimelineEventCreate",
    "TimelineEventUpdate",
    "TimelineEventRef",
    "TimelineConflict",
    "ConsistencyReport",
    "TimelineView",
    # ── timeline 提取 (F14 §5.5) ──
    "ExtractedTimelineEvent",
    "TimelineExtractRequest",
    "TimelineExtractionResult",
    # ── foreshadowing (F13) ──
    "Foreshadowing",
    "ForeshadowingCreate",
    "ForeshadowingUpdate",
    "ForeshadowingStatus",
    "ExtractedForeshadowing",
    "ForeshadowingExtractRequest",
    "ForeshadowingExtractionResult",
]
